# Generated by Django 4.1.3 on 2022-12-13 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('g_kamp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
